# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Wed Sep 02 14:19:58 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 525)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.marca = QtGui.QLineEdit(Dialog)
        self.marca.setObjectName("marca")
        self.verticalLayout.addWidget(self.marca)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.modelo = QtGui.QLineEdit(Dialog)
        self.modelo.setObjectName("modelo")
        self.verticalLayout.addWidget(self.modelo)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.motor = QtGui.QLineEdit(Dialog)
        self.motor.setObjectName("motor")
        self.verticalLayout.addWidget(self.motor)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.peso = QtGui.QLineEdit(Dialog)
        self.peso.setObjectName("peso")
        self.verticalLayout.addWidget(self.peso)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.rendim = QtGui.QLineEdit(Dialog)
        self.rendim.setObjectName("rendim")
        self.verticalLayout.addWidget(self.rendim)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.imagen = QtGui.QLabel(Dialog)
        self.imagen.setObjectName("imagen")
        self.verticalLayout.addWidget(self.imagen)
        self.btn_img = QtGui.QPushButton(Dialog)
        self.btn_img.setObjectName("btn_img")
        self.verticalLayout.addWidget(self.btn_img)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.fecha = QtGui.QLineEdit(Dialog)
        self.fecha.setObjectName("fecha")
        self.verticalLayout.addWidget(self.fecha)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.precio = QtGui.QLineEdit(Dialog)
        self.precio.setObjectName("precio")
        self.verticalLayout.addWidget(self.precio)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.textEdit = QtGui.QTextEdit(Dialog)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.btn_guardar = QtGui.QPushButton(Dialog)
        self.btn_guardar.setObjectName("btn_guardar")
        self.verticalLayout.addWidget(self.btn_guardar)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Marca del Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Modelo del Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Peso", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Rendimiento", None, QtGui.QApplication.UnicodeUTF8))
        self.rendim.setText(QtGui.QApplication.translate("Dialog", "0 km/l", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Imagen", None, QtGui.QApplication.UnicodeUTF8))
        self.imagen.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_img.setText(QtGui.QApplication.translate("Dialog", "Seleccionar una Imagen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Fecha Creacion (Año)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Precio de Venta $", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Descripción: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_guardar.setText(QtGui.QApplication.translate("Dialog", "Registrar Cambios", None, QtGui.QApplication.UnicodeUTF8))

